/*
 * Gestion Produits REST API
 * RESTful API pour la gestion des produits
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.abdel.gestionproduit.testswaggercodegen.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
