
package org.abdel.webServiceExemple.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloImplService", targetNamespace = "http://impl.webServiceExemple.abdel.org/", wsdlLocation = "http://localhost:8081/hello?wsdl")
public class HelloImplService
    extends Service
{

    private final static URL HELLOIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.abdel.webServiceExemple.client.HelloImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.abdel.webServiceExemple.client.HelloImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/hello?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/hello?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOIMPLSERVICE_WSDL_LOCATION = url;
    }

    public HelloImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloImplService() {
        super(HELLOIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.webServiceExemple.abdel.org/", "HelloImplService"));
    }

    /**
     * 
     * @return
     *     returns IHello
     */
    @WebEndpoint(name = "HelloImplPort")
    public IHello getHelloImplPort() {
        return super.getPort(new QName("http://impl.webServiceExemple.abdel.org/", "HelloImplPort"), IHello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHello
     */
    @WebEndpoint(name = "HelloImplPort")
    public IHello getHelloImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webServiceExemple.abdel.org/", "HelloImplPort"), IHello.class, features);
    }

}
