
package org.abdel.webServiceExemple.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IHello", targetNamespace = "http://interfaces.webServiceExemple.abdel.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IHello {


    /**
     * 
     * @param nom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String sayBye(
        @WebParam(name = "nom", partName = "nom")
        String nom);

    /**
     * 
     * @param nom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String sayHello(
        @WebParam(name = "nom", partName = "nom")
        String nom);

}
