/*
 * Gestion Produits REST API
 * RESTful API pour la gestion des produits
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.abdel.gestionproduit.testswaggercodegen.apiapi;

import org.abdel.gestionproduit.testswaggercodegen.ApiException;
import org.abdel.gestionproduit.testswaggercodegen.model.PageProduit;
import org.abdel.gestionproduit.testswaggercodegen.model.Produit;
import org.junit.Ignore;
import org.junit.Test;

import java.util.List;

/**
 * API tests for ProduitServiceApi
 */
@Ignore
public class ProduitServiceApiTest {

    private final ProduitServiceApi api = new ProduitServiceApi();

    
    /**
     * deleteProduit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProduitUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteProduitUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * Get all product
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUsingGETTest() throws ApiException {
        List<Produit> response = api.getAllUsingGET();
    System.out.println(response);
        // TODO: test validations
    }
    
    /**
     * getProduitById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProduitByIdUsingGETTest() throws ApiException {
        Long id = null;
        Produit response = api.getProduitByIdUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * getProduitsByDesign
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProduitsByDesignUsingGETTest() throws ApiException {
        String design = null;
        Integer page = null;
        Integer size = null;
        PageProduit response = api.getProduitsByDesignUsingGET(design, page, size);

        // TODO: test validations
    }
    
    /**
     * getProduitsByDesignation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProduitsByDesignationUsingGETTest() throws ApiException {
        String design = null;
        Integer page = null;
        Integer size = null;
        PageProduit response = api.getProduitsByDesignationUsingGET(design, page, size);

        // TODO: test validations
    }
    
    /**
     * saveProduit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveProduitUsingPOSTTest() throws ApiException {
        Produit produit = null;
        Produit response = api.saveProduitUsingPOST(produit);

        // TODO: test validations
    }
    
    /**
     * saveProduit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveProduitUsingPUTTest() throws ApiException {
        Long id = null;
        Produit produit = null;
        Produit response = api.saveProduitUsingPUT(id, produit);

        // TODO: test validations
    }
    
}
